language: ruby
sudo: required
dist: trusty

env:
  -FONT="SourceSansPro"

notifications:
  email: false

before_install:
- chmod +x ./bin/install-font.sh
- chmod +x ./bin/build.sh

install:
# Install LaTeX
# - sudo apt-get -qq update
# - sudo apt-get install texlive
# - sudo apt-get install texlive-xetex
# Install Fonts
- wget https://github.com/adobe-fonts/source-sans-pro/archive/2.020R-ro/1.075R-it.zip -O SourceSansPro.zip
- unzip SourceSansPro.zip 
- mkdir -p ~/.fonts
- ls -al
- cp source-sans-pro-2.020R-ro-1.075R-it ~/.fonts/
- sudo fs-cache -f -v

script:
- mkdir _build
- ./bin/build.sh