language: ruby
sudo: required
dist: trusty

notifications:
  email: false

before_install:
- chmod +x ./bin/install-font.sh
- chmod +x ./bin/build.sh

install:
- sudo apt-get -qq update
- sudo apt-get install -y texlive-full
- mkdir -p ~/.fonts/
- cp -rf fonts/* ~/.fonts/
- sudo fc-cache -f -v

script:
- mkdir _build
- ./bin/build.sh