sudo: required
dist: trusty

notifications:
  email: false

before_install:
- sudo apt-get -qq update
- sudo apt-get install texlive
- sudo apt-get install texlive-xetex
- sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install fonts-lato
script:
- mkdir _build
- ./build.sh