sudo: required
dist: trusty

before_install:
- sudo apt-get -qq update
- sudo add-apt-repository ppa:texlive-backports/ppa
- sudo apt-get install texlive
- sudo apt-get install texlive-xetex
- sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
script:
- mkdir _build
- xelatex -output-directory=_build -halt-on-error Luke_Sheard_Resume.tex