language: ruby
sudo: required
dist: trusty

notifications:
  email: false

before_install:
- chmod +x ./bin/install-font.sh
- chmod +x ./bin/build.sh

install:
- sudo apt-get -qq update
- sudo apt-get install texlive
- sudo apt-get install texlive-xetex
- sudo apt-get install texlive-fonts-recommended texlive-fonts-extra
- sudo apt-get install fonts-lato
- ./bin/install-font.sh

script:
- mkdir _build
- ./bin/build.sh